services:

  core:
    container_name: core_wow
    image: wow:3.3.5a
    volumes:
      - ./data:/home/wow/server/data
      - ./etc:/home/wow/server/etc
      - ./bin:/home/wow/server/bin
      - ../TrinityCore:/home/wow/TrinityCore
    ports:
      - 3724:3724
      - 8085:8085
    depends_on:
      - database
    stdin_open: true
    restart: no

  database:
    container_name: database_wow
    image: mysql:8.4
    command: --mysql-native-password=ON
    volumes:
      - database:/var/lib/mysql
      - ../TrinityCore/sql:/TrinityCore
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    restart: no

volumes:
  database:
