networks:
  wow:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  core:
    image: wow:core
    build:
      context: .
      dockerfile: "core.Dockerfile"
    container_name: core_wow
    volumes:
      - ./data:/home/wow/server/data
      - ./etc:/home/wow/server/etc
      - ./bin:/home/wow/server/bin
      - ./TrinityCore:/home/wow/TrinityCore
    networks:
      wow:
        ipv4_address: 172.20.0.3
    ports:
      - "3724:3724"
      - "8085:8085"
    depends_on:
      - database
    stdin_open: true
    restart: always
  database:
    image: wow:database
    build:
      context: .
      dockerfile: "database.Dockerfile"
    container_name: database_wow
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./TrinityCore:/TrinityCore
    networks:
      wow:
        ipv4_address: 172.20.0.2
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 220820
    restart: always
